#!/usr/bin/env bash
# INSTALL NGINX

sudo apt-get update
sudo apt-get install -y nginx

printf %s "server {
  listen  80 default_server;
  root    /var/www/html;
  index   index.html index.htm;
}
" >/etc/nginx/sites-available/default
echo "Holberton School" >/var/www/html/index.html
service nginx restart